version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    image: mlflow:latest
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  feast:
    image: feast:latest
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  evidently:
    image: evidently:latest
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

volumes:
  postgres_data:
